### ISSUE TITLE
Error: incorrect header check at Zlib.zlibOnError [as onerror]

### ISSUE THREAD

**Issue by mikuhl-dev** [devsnek/snekfetch#36]
## Version or commit hash:

3.6.4

## Explanation of issue:

error with zlib when going to certain sites.

## Example code to reproduce:
```js
require('snekfetch').get('http://www.gibson.com/News-Lifestyle/Features/en-us/10-Power-Ballads-Fueled-by-Gibson-Guitars.aspx')
	.then(console.log)
	.catch(function(error) {
		console.log('Trying to catch the error, but I cant!')
		console.error(error)
	})
```
Issue occurs in node

**Comment by devsnek** [comment]
fixed in f22d100724d9156cfe2658aac976d4663d39b7d0

**Comment by mikuhl-dev** [comment]
@devsnek It wasn't actually fixed. I feel like its from the Unzip object from CreateUnzip and not the stream.

**Comment by devsnek** [comment]
@MichaelPriebe it actually is attached to the unzip... so whatever your issue is it isn't from that.

**Comment by mikuhl-dev** [comment]
I mean installing 4.0.0 and doing the code above gets me the same error.

**Comment by devsnek** [comment]
@MichaelPriebe the changes haven't been published to npm yet...
